### ISSUE TITLE
Simplify the deployment labels

### ISSUE THREAD

**Issue by woudsma** [swarmlet/swarmlet#61]
The current Traefik deployment labels can be somewhat tricky to understand, a simplified version would be nice.

Turning this:
```yml
labels:
  - swarmlet.port=9000
  - swarmlet.domains=mysite.com,www.mysite.com
  - swarmlet.letsencrypt.email=mail@domain.com
```
Into this:
```yml
labels:
  - traefik.enable=true
  - traefik.http.services.my-service.loadbalancer.server.port=9000
  - traefik.http.routers.my-service.rule=Host(`mysite.com`) || Host(`www.mysite.com`)
  - traefik.http.routers.my-service.entrypoints=http,https
  - traefik.http.routers.my-service.middlewares=redirect@file
  - traefik.http.routers.my-service.tls=true
  - traefik.http.routers.my-service.tls.certresolver=letsencrypt
  - traefik.http.routers.my-service.tls.domains[0].main=mysite.com
  - traefik.http.routers.my-service.tls.domains[0].sans=www.mysite.com
```

When Traefik labels are detected next to Swarmlet labels, the file won't be parsed and only the Traefik labels will apply.

**Comment by fishnux** [comment]
The swarmlet.domains label doesn't allow the specification of a route path. Imagine someone wants to host a blog at example.com/blog instead of blog.example.com. Taking some inspiration from Caddy server, I would suggest:
```yaml
labels:
  - swarmlet.address=example.com/blog,www.example.com/blog
  - swarmlet.address=http://example.com/blog # explicit HTTP protocol (no HTTPS)
```
Thoughts?

Also, regarding the name of the label swarmlet.letsencrypt, Let's Encrypt is not the only ACME certificate provider. Would it make more sense to use some sort of generic name like swarmlet.acme? Currently I'm using swarmlet.lego.email in the development branch (glusterfs/traefikv2), as Lego is the tool we're going to use to fetch TLS certificates from Let's Encrypt (or any other ACME-compatible certificate provider).

**Comment by woudsma** [comment]
Agree. Handling route paths is something I didn't implement yet in the current label parser.
Also good point about the cert provider, I like the more generic `swarmlet.acme` label. This would also allow you to set a different cert resolver in a future update for example. But `swarmlet.lego.<value>` is pretty accurate to the current situation.

**Comment by woudsma** [comment]
I've updated the label parser (rewrote it with Deno).
Users should be able to overwrite the defaults by specifying more specific Swarmlet labels, or by using Traefik labels instead of the simplified Swarmlet labels.

I'm not sure if we should abstract away the `networks` as well, what do you think @fishnux ?
For now I'll push this version to the [`feature/label-parser`](https://github.com/swarmlet/swarmlet/tree/feature/label-parser) branch so we can test things out.

Not sure if this script should run as a service, waiting for input, or if we should just run `docker run --rm -it $SWARMLET_REGISTRY/label-parser $DOCKER_COMPOSE_FILE`. Feedback welcome!

## HTTP
Input:
```yml
version: '3.7'

services:
  web:
    image: hashicorp/http-echo
    command: ['-text', 'Hello World..']
    deploy:
      replicas: 1
      labels:
        - swarmlet.domains=mydomain.com,www.mydomain.com,test.mydomain.com/page
        - swarmlet.port=12345
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
```
Output:
```yml
version: '3.7'
web:
  image: hashicorp/http-echo
  command:
    - '-text'
    - Hello World..
  deploy:
    replicas: 1
    labels:
      - traefik.enable=true
      - traefik.http.routers.web.entrypoints=http
      - >-
        traefik.http.routers.web.rule=Host(`mydomain.com`) ||
        Host(`www.mydomain.com`) || (Host(`test.mydomain.com`) && Path(`/page`))
      - traefik.http.services.web.loadbalancer.server.port=12345
  networks:
    - traefik-public
networks:
  traefik-public:
    external: true
```
## With HTTPS
Input:
```yml
version: '3.7'

services:
  web:
    image: hashicorp/http-echo
    command: ['-text', 'Hello World..']
    deploy:
      replicas: 1
      labels:
        - swarmlet.port=12345
        - swarmlet.domains=mydomain.com,www.mydomain.com,test.mydomain.com/page
        - swarmlet.lego.email=me@mydomain.com
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
```
Output:
```yml
version: '3.7'
web:
  image: hashicorp/http-echo
  command:
    - '-text'
    - Hello World..
  deploy:
    replicas: 1
    labels:
      - traefik.enable=true
      - traefik.http.routers.web.middlewares=redirect@file
      - 'traefik.http.routers.web.entrypoints=http,https'
      - traefik.http.services.web.loadbalancer.server.port=12345
      - >-
        traefik.http.routers.web.rule=Host(`mydomain.com`) ||
        Host(`www.mydomain.com`) || (Host(`test.mydomain.com`) && Path(`/page`))
      - traefik.http.routers.web.tls=true
      - traefik.http.routers.web.tls.certresolver=letsencrypt
      - 'traefik.http.routers.web.tls.domains[0].main=mydomain.com'
      - >-
        traefik.http.routers.web.tls.domains[0].sans=www.mydomain.com,test.mydomain.com
      - traefik.http.routers.web.tls.email=me@mydomain.com
  networks:
    - traefik-public
networks:
  traefik-public:
    external: true
```
