### ISSUE TITLE
Backup/restore functionality

### ISSUE THREAD

**Issue by fishnux** [swarmlet/swarmlet#65]
The ability to backup and restore a Swarmlet cluster is essential for production systems, particularly when dealing with databases. 

A Bash script coupled with something like gobackup and/or rclone would be nice. 

In order to ensure backup consistency on databases I suggest the following additional service labels:
```yaml
labels:
  - swarmlet.backup.before: "./stop_disk_writes.bash"
  - swarmlet.backup.after: "./start_disk_writes.bash"
```
Before a backup procedure starts database containers should stop writing to disk to prevent the creation of an inconsistent backup. The limitation is lifted as soon as the backup procedure finishes. The disk write stand-by is handled by the database application itself through an application-specific command.
