### ISSUE TITLE
Offline installation 

### ISSUE THREAD

**Issue by rwanito** [swarmlet/swarmlet#81]
Hi !

I've just find your project and I'm very glad to find it !
I have a suggestion, maybe, is it possible to you to make installation offline too ?

In some case, I work on intranet and It would be a great feature !

I have another question, but it's not the same subject.
For 2 nodes server, is glusterFS stable ?

Thanks for your work !

**Comment by woudsma** [comment]
Hi there! Thanks for trying out Swarmlet, and excuse my late reply.
Unfortunately it's not possible to install Swarmlet without an internet connection on the host.
We're installing quite some dependencies using `apt-get` and `pip` for example, I'm not sure how it would work when you would try to cache/bundle this up.

GlusterFS in itself is stable, but I have to finalize some work before the Gluster volume is shared with new hosts.
I did a large rewrite over the last months, this is something that I hope to finish ASAP 🙂 
If you have any more question, don't hesitate to ask or to join our Slack channel!

**Comment by rwanito** [comment]
Thanks for your reply !

I have apt mirrors but no mirror for pip.
Do you think some requirements from pip can be installed with apt ? 
For example : django -> python3-django, docker -> python3-docker ?
Or make any settings to change url of repo for apt and pip both ?
Even if apt is very practical. 

I follow your work attentively and I thank you again for your work !

**Comment by woudsma** [comment]
I'm not sure, most installation stuff is handled by Ansible now, feel free to play around with the playbooks/tasks around this issue.
This is where we install some packages using pip: https://github.com/swarmlet/swarmlet/blob/master/src/ansible/playbooks/setup.yml

**Comment by rwanito** [comment]
Okay, I saw.
In my case, If I wanted to get work it offline, I will replace : 
```yaml
    - name: install pre-requirements
      apt:
        pkg:
          - acl
          - curl
          - apache2-utils
          - software-properties-common
          - ca-certificates
          - gnupg-agent
          - moreutils
          - wget
          - tree
          - libpcre3
          - xfsprogs
          - btrfs-progs

    - name: install pip
      apt:
        pkg:
          - python-pip
          - python3-pip

    - name: install pip modules
      pip:
        name:
          - netaddr
          - pyvmomi
          - docker
          - requests
```
by
```yaml
    - name: install pre-requirements
      apt:
        pkg:
          - acl
          - curl
          - apache2-utils
          - software-properties-common
          - ca-certificates
          - gnupg-agent
          - moreutils
          - wget
          - tree
          - libpcre3
          - xfsprogs
          - btrfs-progs
          - python3-netaddr
          - python3-pyvmomi
          - python3-docker
          - python3-requests
```

Just try with (Tried on Ubuntu 20.10) :
```bash
$ apt search python3 | grep docker
python3-docker/groovy,groovy 4.1.0-1.2 all
  Python 3 wrapper to access docker.io's control socket
```
Did you see what I try to say ?

I'm trying that because It's more complicated to serve a pip mirror than a apt mirror on my intranet.
